Features/file
Team-Discipline/Xlack-Backend pull request #61
Opened 2022-12-23 07:13 UTC by gyuriiiii

2022-12-23 08:35 UTC, kreimben commented on file/serializers.py
> +    uploaded_by = serializers.PrimaryKeyRelatedField(many=False, read_only=True)
@gyuriiiii 

우리가 custom user도 구현하고 거기에 대한 serializer도 구현한것 같은데,
여기 `serializers.PrimaryKeyRelatedField` 보단 기왕이면 우리가 구현한 serializer를 넣는게 더 좋을것 같은데... read_only=True로 하고

many=False는 자동으로 들어가는거라 명시 안해줘도 돼.

2022-12-23 08:37 UTC, kreimben commented on file/views.py
> +            file.delete()
@gyuriiiii 

이건 너무 생각없이 코드 가져온것 같은데...

이거는 채팅 치면서 파일을 하나씩 업로드 할 때마다 기존에 업로드한걸 지우는거잖아.

다시 수정해.

2022-12-23 08:38 UTC, kreimben requested changes
의견들 남겨 놨으니 커멘트 하나씩 다 수정할 수 있도록.

2022-12-24 13:26 UTC, kreimben approved these changes
approved.

2022-12-24 13:35 UTC, kreimben commented
@ds1sqe @ryankimjh00

2022-12-24 13:42 UTC, ds1sqe approved these changes
Approved

2022-12-24 14:34 UTC, ryankimjh00 approved these changes
리뷰완료👍

2022-12-24 14:34 UTC, merged